# CONFIGURATION DU SITE - MENTOR MALONGA
# ==============================================================================

# --- Informations de base ---
title: Mentor MALONGA | Data Analyst & BI Developer 
description: "Expert en analyse de données et BI, alliant la rigueur de l'électronique à la puissance de Microsoft Fabric et Power BI."
email: mentormalonga17@gmail.com
author: Mentor Malonga

# --- URL du site ---
# Remplace 'ton-pseudo' par ton vrai nom d'utilisateur GitHub
url: "https://Mentor077.github.io" 
baseurl: "" # Laisse vide si ton site est à la racine (ex: ton-pseudo.github.io)

# --- Thème (Choisis-en un supporté par GitHub Pages) ---
# Exemples: jekyll-theme-minimal, jekyll-theme-architect, jekyll-theme-cayman
theme: jekyll-theme-minimal 

# --- Réseaux Sociaux & Liens ---
social:
  linkedin: "www.linkedin.com/in/mentor-malonga"
  github: "https://github.com/Mentor077"
